### ISSUE TITLE
Requests missing from requirments.txt?

### ISSUE THREAD

**Issue by ghost** [kendricktan/misocoin#2]
File "./misocoind.py", line 20, in <module>
    from misocoin.sync import misocoin_cli, MisocoinRequestHandler
  File "/home/****/github/misocoin/misocoin/sync.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

i installed with pip and it then worked.

**Comment by kendricktan** [comment]
Done. Thanks!
